#!/usr/bin/env bash

set -e

mkdir -p ~/.gradle

props="org.gradle.daemon=false\n
org.gradle.workers.max=2\n
kotlin.incremental=false\n
kotlin.compiler.execution.strategy=in-process\n
org.gradle.jvmargs=-Xmx3g\n
GLOBALLY_DYNAMIC_KEYSTORE_PATH=${GLOBALLY_DYNAMIC_KEYSTORE_PATH}\n
GLOBALLY_DYNAMIC_KEYSTORE_PASSWORD=${GLOBALLY_DYNAMIC_KEYSTORE_PASSWORD}\n
GLOBALLY_DYNAMIC_KEY_ALIAS=${GLOBALLY_DYNAMIC_KEY_ALIAS}\n
GLOBALLY_DYNAMIC_KEY_PASSWORD=${GLOBALLY_DYNAMIC_KEY_PASSWORD}\n
GLOBALLY_DYNAMIC_USERNAME=${GLOBALLY_DYNAMIC_USERNAME}\n
GLOBALLY_DYNAMIC_PASSWORD=${GLOBALLY_DYNAMIC_PASSWORD}\n
"

printf ${props} > ~/.gradle/gradle.properties
