#!/usr/bin/env bash

set -e

# Create a bucket in Google Cloud Storage where bundles will be stored
bucket_id=globallydynamic_storage
gsutil mb -l eu "gs://${bucket_id}"

echo "
export GLOBALLY_DYNAMIC_PORT=9090
export GLOBALLY_DYNAMIC_USERNAME=${GLOBALLY_DYNAMIC_USERNAME}
export GLOBALLY_DYNAMIC_PASSWORD=${GLOBALLY_DYNAMIC_PASSWORD}
export GLOBALLY_DYNAMIC_STORAGE_BACKEND=gcp
export GLOBALLY_DYNAMIC_GCP_BUCKET_ID=${bucket_id}
export GLOBALLY_DYNAMIC_HTTPS_REDIRECT=false
export GLOBALLY_DYNAMIC_OVERRIDE_EXISTING_BUNDLES=false
export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
export ANDROID_SDK_ROOT=/opt/android/sdk
export ANDROID_HOME=/opt/android/sdk
" > vm_environment

#Create VM instance
gcloud compute instances create globallydynamic \
    --tags=http-server,https-server \
    --scopes=cloud-platform \
    --zone=europe-west1-b \
    --metadata-from-file=environment=vm_environment,startup-script=$(pwd)/compute_engine_startup

# Allow incoming traffic on port 8080
gcloud compute firewall-rules create allow-http-8080 \
    --allow tcp:8080 \
    --source-ranges 0.0.0.0/0 \
    --target-tags http-server \
    --description "Allow port 8080 access to http-server"
